In [13]:
import kagglehub

path = kagglehub.dataset_download("ex0ticone/house-prices-of-sao-paulo-city")

print(path)

C:\Users\bibif\.cache\kagglehub\datasets\ex0ticone\house-prices-of-sao-paulo-city\versions\1

In [14]:
for col in df.select_dtypes(include='object').columns:
    try:
        df[col] = df[col].apply(
            lambda x: x.encode('latin1').decode('utf-8')
            if isinstance(x, str) else x
        )
    except:
        pass

In [15]:
print(df['cidade'].head())
print(df['bairro'].head())
print(df['tipo_imovel'].head())

0    SÃ£o Paulo
1    SÃ£o Paulo
2    SÃ£o Paulo
3    SÃ£o Paulo
4    SÃ£o Paulo
Name: cidade, dtype: object
0                Jardim da SaÃºde
1    Vila Santa Teresa (Zona Sul)
2                      Bela Vista
3                   Vila OlÃ­mpia
4                        ParaÃ­so
Name: bairro, dtype: object
0    Casa de dois andares
1                    Casa
2               Comercial
3             Apartamento
4             Apartamento
Name: tipo_imovel, dtype: object

In [16]:
print(repr(df['cidade'].iloc[0]))
print(repr(df['bairro'].iloc[0]))
print(repr(df['tipo_imovel'].iloc[2]))

'SÃ£o Paulo'
'Jardim da SaÃºde'
'Comercial'

In [17]:
texto = 'SÃ£o Paulo'

corrigido = texto.encode('latin1').decode('utf-8')

print(corrigido)

São Paulo

In [21]:
for valor in df['cidade'].dropna().unique()[:20]:
    print(repr(valor))

'SÃ£o Paulo'
'ParaÃ\xadso'
'Rua SÃ£o G'
'Vila AmÃ©lia'
'Vila ButantÃ£'
'Vila OlÃ\xadm'
'Ã\x81gua Branca'
'HigienÃ³polis'
'Bela AlianÃ§a'
'IndianÃ³polis'
'Rua BelÃ©m'
'JaguarÃ©'
'Vila OlÃ\xadmpia'
'Vila SÃ´nia'
'Vila CarrÃ£o'
'ConsolaÃ§Ã£o'
'CupecÃª'
'Avenida IraÃ\xad'
'Parque IpÃª'
'SatuapÃ©'

In [20]:
print(df.columns.tolist())

['logradouro', 'numero', 'bairro', 'cep', 'cidade', 'tipo_imovel', 'area_util', 'banheiros', 'suites', 'quartos', 'vagas_garagem', 'anuncio_criado', 'tipo_anuncio', 'preco_venda', 'taxa_condominio', 'periodicidade', 'preco_aluguel', 'iptu_ano']

In [22]:
texto = 'SÃ£o Paulo'
print(texto.encode('latin1').decode('utf-8'))

São Paulo

In [23]:
def corrigir(texto):
    try:
        return texto.encode('latin1').decode('utf-8')
    except:
        return texto

for col in df.select_dtypes(include='object'):
    df[col] = df[col].astype(str).apply(corrigir)

In [24]:
for col in df.select_dtypes(include='object'):
    print(col)
    print(df[col].dropna().head())
    print()

logradouro
0    Rua Juvenal Galeno
1           Rua Juruaba
2      Avenida Paulista
3          Rua Alvorada
4          Rua Curitiba
Name: logradouro, dtype: object

numero
0      53
1      16
2     402
3    1190
4     380
Name: numero, dtype: object

bairro
0                 Jardim da Saúde
1    Vila Santa Teresa (Zona Sul)
2                      Bela Vista
3                    Vila Olímpia
4                         Paraíso
Name: bairro, dtype: object

cidade
0    São Paulo
1    São Paulo
2    São Paulo
3    São Paulo
4    São Paulo
Name: cidade, dtype: object

tipo_imovel
0    Casa de dois andares
1                    Casa
2               Comercial
3             Apartamento
4             Apartamento
Name: tipo_imovel, dtype: object

anuncio_criado
0    2017-02-07
1    2016-03-21
2    2018-12-18
3    2018-10-26
4    2018-12-14
Name: anuncio_criado, dtype: object

tipo_anuncio
0      Venda
1      Venda
2    Locação
3      Venda
4      Venda
Name: tipo_anuncio, dtype: object

periodicidade
0        nan
1        nan
2    MONTHLY
3        nan
4        nan
Name: periodicidade, dtype: object

In [25]:
print(df.shape)

df.info()

df.isnull().sum()

(133964, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133964 entries, 0 to 133963
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   logradouro       133964 non-null  object
 1   numero           133964 non-null  object
 2   bairro           133964 non-null  object
 3   cep              128056 non-null  float64
 4   cidade           133964 non-null  object
 5   tipo_imovel      133964 non-null  object
 6   area_util        130868 non-null  float64
 7   banheiros        133051 non-null  float64
 8   suites           120347 non-null  float64
 9   quartos          130945 non-null  float64
 10  vagas_garagem    129539 non-null  float64
 11  anuncio_criado   133964 non-null  object
 12  tipo_anuncio     133964 non-null  object
 13  preco_venda      133964 non-null  int64
 14  taxa_condominio  117127 non-null  float64
 15  periodicidade    133964 non-null  object
 16  preco_aluguel    28714 non-null   float64
 17  iptu_ano         114612 non-null  float64
dtypes: float64(9), int64(1), object(8)
memory usage: 18.4+ MB

logradouro              0
numero                  0
bairro                  0
cep                  5908
cidade                  0
tipo_imovel             0
area_util            3096
banheiros             913
suites              13617
quartos              3019
vagas_garagem        4425
anuncio_criado          0
tipo_anuncio            0
preco_venda             0
taxa_condominio     16837
periodicidade           0
preco_aluguel      105250
iptu_ano            19352
dtype: int64

In [26]:
#Filtrando apenas imóveis à venda
df_venda = df[df['tipo_anuncio'] == 'Venda'].copy()
print(df_venda.shape)

(105332, 18)

In [27]:
colunas = [
    'bairro',
    'tipo_imovel',
    'area_util',
    'banheiros',
    'suites',
    'quartos',
    'vagas_garagem',
    'preco_venda'
]

df_ml = df_venda[colunas].copy()

df_ml.isnull().sum()

bairro              0
tipo_imovel         0
area_util        2569
banheiros         668
suites           9705
quartos          1279
vagas_garagem    2965
preco_venda         0
dtype: int64

In [30]:
df_ml = df_venda[
    [
        'bairro',
        'tipo_imovel',
        'area_util',
        'banheiros',
        'suites',
        'quartos',
        'vagas_garagem',
        'preco_venda'
    ]
].copy()

df_ml = df_ml.dropna()
print(df_ml.shape)

(92846, 8)

In [31]:
corr = df_ml.corr(numeric_only=True)

print(
    corr['preco_venda']
    .sort_values(ascending=False)
)

preco_venda      1.000000
vagas_garagem    0.408908
suites           0.351064
banheiros        0.307495
quartos          0.094139
area_util        0.046861
Name: preco_venda, dtype: float64

In [32]:
df_ml[['area_util', 'preco_venda']].describe()

          area_util   preco_venda
count  9.284600e+04  9.284600e+04
mean   1.983888e+02  8.715192e+05
std    6.756169e+03  1.429237e+06
min    1.000000e+00  7.000000e+03
25%    6.700000e+01  3.150000e+05
50%    1.100000e+02  5.039990e+05
75%    1.880000e+02  9.100000e+05
max    2.025000e+06  8.400000e+07

In [33]:
df_venda['preco_venda'].describe()

count    1.053320e+05
mean     8.415624e+05
std      1.434909e+06
min      7.000000e+03
25%      2.968000e+05
50%      4.822990e+05
75%      8.869000e+05
max      8.400000e+07
Name: preco_venda, dtype: float64

In [36]:
#Procurando registros muito grandes 
df_ml.sort_values(
    'area_util',
    ascending=False
)[['area_util', 'preco_venda']].head(20)

        area_util  preco_venda
116402  2025000.0      1750000
108893   226000.0     70000000
71139    160000.0       525000
91585    129000.0      1373890
57724    110788.0      2800000
67973     90000.0       525000
117503    62000.0     17880800
886       60000.0       700000
35070     35000.0     24500000
94147     34293.0      4900000
113318    33000.0      1274000
104413    32773.0      1260000
84570     30220.0     18550000
117515    30000.0     31499999
45156     29300.0     16800000
69053     26995.0     23100000
51338     26000.0      1260000
70417     23000.0       560000
16201     19258.0       730100
11992     19147.0     23100000

In [37]:
df_venda['tipo_imovel'].value_counts()

tipo_imovel
Apartamento               64146
Casa de dois andares      16758
Casa                       8195
Condomínio                 3821
Cobertura                  2511
Comercial                  2217
Flat                       2101
Escritório                 2070
Loteamento Residencial     1372
Loteamento Comercial        677
Depósito                    648
Kitnet                      475
Loja                        175
Prédio Residencial          108
Prédio Comercial             37
Clínica                      11
Casa de Campo                 8
Fazenda                       2
Name: count, dtype: int64

In [38]:
#Foram mantidos apenas imóveis residenciais (apartamentos, casas, coberturas, flats, kitnets e imóveis em condomínio), 
#pois imóveis comerciais, terrenos e propriedades rurais possuem dinâmicas de precificação distintas, o que poderia 
#introduzir ruído e prejudicar o desempenho dos modelos preditivos.

tipos_residenciais = [
    'Apartamento',
    'Casa',
    'Casa de dois andares',
    'Condomínio',
    'Cobertura',
    'Flat',
    'Kitnet'
]

df_res = df_venda[
    df_venda['tipo_imovel'].isin(tipos_residenciais)
].copy()
print(df_res.shape)

(98007, 18)

In [39]:
print(df_res['area_util'].quantile(0.99))
print(df_res['area_util'].quantile(0.995))

609.0
750.0

In [40]:
df_res = df_res[df_res['area_util'] <= 750]
corr = df_res[
    [
        'area_util',
        'banheiros',
        'suites',
        'quartos',
        'vagas_garagem',
        'preco_venda'
    ]
].corr()

print(corr['preco_venda'].sort_values(ascending=False))

preco_venda      1.000000
area_util        0.681855
suites           0.523110
banheiros        0.449633
vagas_garagem    0.429215
quartos          0.176255
Name: preco_venda, dtype: float64

In [41]:
df_res['preco_venda'].describe()

count    9.585000e+04
mean     7.601284e+05
std      9.796591e+05
min      1.050000e+04
25%      2.940000e+05
50%      4.689990e+05
75%      8.400000e+05
max      7.420000e+07
Name: preco_venda, dtype: float64

In [42]:
df_res.sort_values(
    'preco_venda',
    ascending=False
)[
    ['tipo_imovel','bairro','area_util','quartos','preco_venda']
].head(20)

        tipo_imovel               bairro  area_util  quartos  preco_venda
3076    Apartamento      Jardim Paulista      190.0      3.0     74200000
127239  Apartamento              São Pau       48.0      1.0     25434920
87613     Cobertura                Moema      729.0      4.0     21000000
95777   Apartamento  Vila Nova Conceição      539.0      3.0     20720000
82480   Apartamento  Vila Nova Conceição      539.0      3.0     19600000
88205   Apartamento  Vila Nova Conceição      539.0      3.0     19600000
84123   Apartamento                Moema      539.0      5.0     19250000
91053   Apartamento  Vila Nova Conceição      726.0      4.0     18550000
110712    Cobertura      Cerqueira César      672.0      3.0     17990000
110709  Apartamento      Cerqueira César      672.0      4.0     17500000
97413   Apartamento           Itaim Bibi      570.0      4.0     17296744
2277           Casa              Jardins      742.0      5.0     16800000
96129   Apartamento           Itaim Bibi      573.0      4.0     16449999
94014   Apartamento           Itaim Bibi      570.0      4.0     16099999
97431   Apartamento           Itaim Bibi      570.0      5.0     16099999
34742   Apartamento      Jardim Paulista      587.0      4.0     15679999
89416   Apartamento      Jardim Panorama      749.0      6.0     15399999
86060   Apartamento              Paraíso      632.0      4.0     15399999
93970   Apartamento        Cidade Jardim      749.0      5.0     15399999
94352   Apartamento      Jardim Panorama      749.0      5.0     15399999

In [43]:
df_res.loc[3076]

logradouro         Alameda Campinas
numero                          nan
bairro              Jardim Paulista
cep                       1404001.0
cidade                    São Paulo
tipo_imovel             Apartamento
area_util                     190.0
banheiros                       2.0
suites                          1.0
quartos                         3.0
vagas_garagem                   2.0
anuncio_criado           2014-10-14
tipo_anuncio                  Venda
preco_venda                74200000
taxa_condominio              1260.0
periodicidade                   nan
preco_aluguel                   NaN
iptu_ano                      350.0
Name: 3076, dtype: object

In [44]:
df_res['bairro'].value_counts().head(20)

bairro
Santana                2221
Jardim Paulista        2093
Vila Mariana           1931
Pinheiros              1893
Higienópolis           1851
Mooca                  1677
Indianópolis           1452
Bela Vista             1392
Campo Belo             1345
Perdizes               1275
Consolação             1245
Tatuapé                1201
Ipiranga               1176
Brooklin Paulista      1132
Jardim Vila Mariana    1119
Cerqueira César        1076
Lauzane Paulista       1069
Itaim Bibi             1034
Vila Carrão            1004
Moema                   939
Name: count, dtype: int64

In [45]:
df_res['bairro'].nunique()

1613

In [46]:
df_res['bairro'].value_counts().tail(50)

bairro
Conjunto Habitacional Marechal Mascarenhas de Morais    1
Conjunto Promorar Sapopemba                             1
Rua Édison                                              1
Vila Nova Utinga                                        1
Rua Flórida                                             1
Iguatemi                                                1
Jardim Rodolfo Pirani                                   1
Parque Planalto                                         1
Rua Antônio Carlos da Fonseca                           1
Jardim Grimaldi                                         1
Alameda dos Guat                                        1
Vl Firmiano                                             1
vila prudente                                           1
Aosque da Saúde                                         1
Jd S Roberto                                            1
Parelheiros                                             1
Rua Sansão Alves dos Santos                             1
Jardim Mimar                                            1
Rua Percílio Neto                                       1
Chac. Santo Anton                                       1
Rua Panônia                                             1
Jdim América                                            1
Rua José Maria Lisboa                                   1
Rua Itambé                                              1
Gamelinha                                               1
Rua Cândido Lac                                         1
Jardim São Remo                                         1
CerqMarquês de                                          1
Rua do Paraíso                                          1
Higienólo                                               1
Jardim São José (Artur Alvim)                           1
Rua Anália Franco                                       1
Cerqueiral Teles                                        1
Jd D Abril                                              1
Vila Sao Domingos                                       1
Conjunto Habitacional Inácio Monteiro                   1
Recanto Morumbi                                         1
Jardim Imperial                                         1
Água Ralo                                               1
Rua Hemisfério                                          1
Rua Inácio Pereira d                                    1
Conjunto Habitacional Fazenda do Carmo                  1
Jard Paulista                                           1
Rua Abílio Soares                                       1
Rua do Lavapés                                          1
Adalgisa                                                1
Vila Sao Luis(Zona Oeste)                               1
Rua Cândida Medeiros da Silva                           1
Rua Mário Amaral                                        1
Cidade São Fran                                         1
Name: count, dtype: int64

In [47]:
contagem = df_res['bairro'].value_counts()

bairros_validos = contagem[contagem >= 20].index

df_res = df_res[df_res['bairro'].isin(bairros_validos)]

In [48]:
df_res['bairro'].nunique()

491

In [50]:
antes = len(df_res)

contagem = df_res['bairro'].value_counts()
bairros_validos = contagem[contagem >= 20].index

df_res_filtrado = df_res[
    df_res['bairro'].isin(bairros_validos)
]

depois = len(df_res_filtrado)

print("Antes:", antes)
print("Depois:", depois)
print("Perda (%):", (antes - depois)/antes*100)

Antes: 90535
Depois: 90535
Perda (%): 0.0

In [51]:
df_final = df_res[
    [
        'bairro',
        'tipo_imovel',
        'area_util',
        'banheiros',
        'suites',
        'quartos',
        'vagas_garagem',
        'preco_venda'
    ]
].dropna()

df_final.to_csv(
    'imoveis_sp_limpo.csv',
    index=False,
    encoding='utf-8-sig'
)